# Site settings
title: Gabriel Reis
email: gabr.rreis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gabriel-rreis.github.io" # the base hostname & protocol for your site

twitter_username: vaguelyRobotic
github_username: gabriel-rreis

# Build settings
markdown: kramdown
